import Link from "next/link";
import { getCatalogue } from "@/lib/catalogue/server";
import { promotionActive, whatsappLink } from "@/lib/catalogue/domain";
import { CatalogueNotice, ServiceCard, StoreFooter, StoreHeader } from "@/components/storefront";
export async function generateMetadata() {
  const { settings } = await getCatalogue();
  return { title: `${settings.name} — Services, abonnements et produits`, description: settings.welcome_text, openGraph: { title: settings.name, description: settings.welcome_text, locale: "fr_SN", type: "website" } };
}
export default async function Home() {
  const catalogue = await getCatalogue(); const { settings, services, categories, now } = catalogue;
  const featured = services.filter((s) => s.is_featured); const popular = (featured.length ? featured : services).slice(0, 4);
  const promotions = services.filter((s) => promotionActive(s, now));
  return <main className="min-h-screen overflow-hidden bg-[#050816] text-white"><StoreHeader settings={settings} /><CatalogueNotice catalogue={catalogue} />
    <section className="relative border-b border-white/10"><div className="pointer-events-none absolute -right-20 top-0 h-96 w-96 rounded-full bg-purple-600/20 blur-[100px]" />
      <div className="relative mx-auto grid max-w-7xl gap-10 px-4 py-14 sm:px-6 sm:py-20 lg:grid-cols-[1.25fr_.75fr] lg:items-center"><div><p className="inline-flex rounded-full border border-blue-400/20 bg-blue-400/10 px-4 py-2 text-xs font-bold text-blue-200">Votre boutique de confiance</p><h1 className="mt-6 max-w-3xl text-4xl font-black leading-tight tracking-tight sm:text-6xl">{settings.welcome_text}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-400">Abonnements, outils et services pour vos envies et vos projets. Des tarifs clairs, un paiement simple et une assistance sur WhatsApp.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/boutique" className="btn-primary">Découvrir les offres →</Link><a className="btn-secondary" href={whatsappLink(settings.whatsapp_number, `Bonjour ${settings.name}, j’ai une question sur vos offres.`)} target="_blank" rel="noopener noreferrer">Discuter sur WhatsApp</a></div></div>
        <aside className="rounded-[32px] border border-white/15 bg-white/5 p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-300">Simple, du choix à la réception</p><ol className="mt-6 space-y-5">{[["Choisissez votre offre", "Le tarif et la durée sont indiqués sur chaque fiche."], ["Payez au numéro officiel", "Wave ou Orange Money, selon votre préférence."], ["Recevez votre service", settings.delivery_info]].map(([title, detail], i) => <li key={title} className="flex gap-4"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-blue-500/20 font-black text-blue-200">{i + 1}</span><div><p className="font-bold">{title}</p><p className="mt-1 text-sm leading-6 text-slate-400">{detail}</p></div></li>)}</ol></aside>
      </div></section>
    <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-400">À découvrir</p><h2 className="mt-3 text-3xl font-black">Nos offres en avant</h2></div><Link href="/boutique" className="text-sm font-bold text-blue-300">Tout le catalogue →</Link></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{popular.map((s) => <ServiceCard key={s.id} service={s} now={now} category={categories.find((c) => c.id === s.category_id)?.name} />)}</div>{!popular.length && <p className="rounded-2xl border border-white/10 p-6 text-slate-400">Nos offres seront bientôt disponibles. Contactez-nous pour en savoir plus.</p>}</section>
    {promotions.length > 0 && <section className="mx-auto max-w-7xl px-4 pb-14 sm:px-6"><h2 className="mb-7 text-3xl font-black">Les promotions du moment</h2><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{promotions.map((s) => <ServiceCard key={s.id} service={s} now={now} category={categories.find((c) => c.id === s.category_id)?.name} />)}</div></section>}
    <section className="border-y border-white/10 bg-white/[0.02] py-12"><div className="mx-auto grid max-w-7xl gap-6 px-4 sm:grid-cols-3 sm:px-6">{[["Paiement simple", "Wave et Orange Money aux coordonnées officielles affichées dans la commande."], ["Accompagnement direct", "Une question sur une offre ? Notre équipe répond sur WhatsApp."], ["Réception guidée", settings.delivery_info]].map(([title, detail]) => <div key={title}><h2 className="font-black text-blue-200">{title}</h2><p className="mt-3 text-sm leading-7 text-slate-400">{detail}</p></div>)}</div></section>
    <section className="mx-auto max-w-5xl px-4 py-14 text-center sm:px-6"><h2 className="text-3xl font-black">Une question avant de commander ?</h2><p className="mt-4 text-slate-400">Nous vous aidons à choisir l’offre adaptée.</p><a href={whatsappLink(settings.whatsapp_number, `Bonjour ${settings.name}, pouvez-vous m’aider à choisir une offre ?`)} target="_blank" rel="noopener noreferrer" className="btn-primary mt-7 inline-flex">Contacter {settings.name}</a></section><StoreFooter settings={settings} />
  </main>;
}
