-- Tarifs corrigés selon la demande du propriétaire. Aucune exécution automatique.
-- CapCut Pro : durée non précisée par le propriétaire, aucun abonnement mensuel supposé.
-- GÉNÉRÉ depuis lib/catalogue/initial.json. Ne pas modifier les prix ici.
-- Après 001, exécution manuelle. Ne remplace jamais les données déjà présentes.
begin;
lock table public.products in share row exclusive mode;
insert into public.categories (id, name, slug, is_active, sort_order) select '10000000-0000-4000-8000-000000000001', 'Streaming', 'streaming', true, 0 on conflict do nothing;
insert into public.categories (id, name, slug, is_active, sort_order) select '10000000-0000-4000-8000-000000000002', 'Intelligence artificielle', 'intelligence-artificielle', true, 1 on conflict do nothing;
insert into public.categories (id, name, slug, is_active, sort_order) select '10000000-0000-4000-8000-000000000003', 'Création', 'creation', true, 2 on conflict do nothing;
insert into public.categories (id, name, slug, is_active, sort_order) select '10000000-0000-4000-8000-000000000004', 'Musique', 'musique', true, 3 on conflict do nothing;
insert into public.categories (id, name, slug, is_active, sort_order) select '10000000-0000-4000-8000-000000000005', 'Logiciels', 'logiciels', true, 4 on conflict do nothing;
insert into public.categories (id, name, slug, is_active, sort_order) select '10000000-0000-4000-8000-000000000006', 'Réseaux sociaux', 'reseaux-sociaux', true, 5 on conflict do nothing;
insert into public.products (id, name, description, category, price, duration, image, active, slug, old_price, promotion_enabled, promo_starts_at, promo_ends_at, is_featured, sort_order, quote_only, details) select '10000000-0000-4000-8000-000000000100', 'Netflix', 'Profitez de vos films et séries préférés. Chaque profil est sécurisé.', 'Streaming', 5000, '1 mois', '/services/netflix.webp', true, 'netflix', NULL, false, NULL, NULL, true, 0, false, '{"short_description":"Profitez de vos films et séries préférés. Chaque profil est sécurisé.","icon":"N","whatsapp_enabled":true,"button_text":"Commander","order_instructions":"","order_fields":[],"kind":"subscription","stock":null,"unit":"","variant_label":"","delivery_info":"","archived_at":null}' where not exists (select 1 from public.products where id='10000000-0000-4000-8000-000000000100' or slug='netflix' or lower(btrim(name))=lower('Netflix')) on conflict do nothing;
insert into public.products (id, name, description, category, price, duration, image, active, slug, old_price, promotion_enabled, promo_starts_at, promo_ends_at, is_featured, sort_order, quote_only, details) select '10000000-0000-4000-8000-000000000101', 'Prime Video', 'Films, séries et programmes exclusifs.', 'Streaming', 5000, '1 mois', '/services/prime-video.webp', true, 'prime-video', NULL, false, NULL, NULL, true, 1, false, '{"short_description":"Films, séries et programmes exclusifs.","icon":"P","whatsapp_enabled":true,"button_text":"Commander","order_instructions":"","order_fields":[],"kind":"subscription","stock":null,"unit":"","variant_label":"","delivery_info":"","archived_at":null}' where not exists (select 1 from public.products where id='10000000-0000-4000-8000-000000000101' or slug='prime-video' or lower(btrim(name))=lower('Prime Video')) on conflict do nothing;
insert into public.products (id, name, description, category, price, duration, image, active, slug, old_price, promotion_enabled, promo_starts_at, promo_ends_at, is_featured, sort_order, quote_only, details) select '10000000-0000-4000-8000-000000000102', 'Disney+', 'Disney, Marvel, Pixar, Star Wars et bien plus.', 'Streaming', 11000, '1 mois', '/services/disney-plus.webp', true, 'disney-plus', NULL, false, NULL, NULL, true, 2, false, '{"short_description":"Disney, Marvel, Pixar, Star Wars et bien plus.","icon":"D+","whatsapp_enabled":true,"button_text":"Commander","order_instructions":"","order_fields":[],"kind":"subscription","stock":null,"unit":"","variant_label":"","delivery_info":"","archived_at":null}' where not exists (select 1 from public.products where id='10000000-0000-4000-8000-000000000102' or slug='disney-plus' or lower(btrim(name))=lower('Disney+')) on conflict do nothing;
insert into public.products (id, name, description, category, price, duration, image, active, slug, old_price, promotion_enabled, promo_starts_at, promo_ends_at, is_featured, sort_order, quote_only, details) select '10000000-0000-4000-8000-000000000103', 'ChatGPT', 'Un assistant intelligent pour le travail, les études et vos projets.', 'Intelligence artificielle', 6500, '1 mois', '/services/chatgpt.webp', true, 'chatgpt', 7500, true, NULL, NULL, true, 3, false, '{"short_description":"Un assistant intelligent pour le travail, les études et vos projets.","icon":"AI","whatsapp_enabled":true,"button_text":"Commander","order_instructions":"","order_fields":[],"kind":"subscription","stock":null,"unit":"","variant_label":"","delivery_info":"","archived_at":null}' where not exists (select 1 from public.products where id='10000000-0000-4000-8000-000000000103' or slug='chatgpt' or lower(btrim(name))=lower('ChatGPT')) on conflict do nothing;
insert into public.products (id, name, description, category, price, duration, image, active, slug, old_price, promotion_enabled, promo_starts_at, promo_ends_at, is_featured, sort_order, quote_only, details) select '10000000-0000-4000-8000-000000000104', 'Canva Pro', 'Créez facilement des affiches, vidéos et visuels professionnels.', 'Création', 15000, '1 an', '/services/canva-pro.webp', true, 'canva-pro', NULL, false, NULL, NULL, false, 4, false, '{"short_description":"Créez facilement des affiches, vidéos et visuels professionnels.","icon":"C","whatsapp_enabled":true,"button_text":"Commander","order_instructions":"","order_fields":[],"kind":"subscription","stock":null,"unit":"","variant_label":"","delivery_info":"","archived_at":null}' where not exists (select 1 from public.products where id='10000000-0000-4000-8000-000000000104' or slug='canva-pro' or lower(btrim(name))=lower('Canva Pro')) on conflict do nothing;
insert into public.products (id, name, description, category, price, duration, image, active, slug, old_price, promotion_enabled, promo_starts_at, promo_ends_at, is_featured, sort_order, quote_only, details) select '10000000-0000-4000-8000-000000000105', 'Spotify Premium', 'Écoutez votre musique préférée sans interruption.', 'Musique', 3500, '1 mois', '/services/spotify-premium.webp', true, 'spotify-premium', NULL, false, NULL, NULL, false, 5, false, '{"short_description":"Écoutez votre musique préférée sans interruption.","icon":"S","whatsapp_enabled":true,"button_text":"Commander","order_instructions":"","order_fields":[],"kind":"subscription","stock":null,"unit":"","variant_label":"","delivery_info":"","archived_at":null}' where not exists (select 1 from public.products where id='10000000-0000-4000-8000-000000000105' or slug='spotify-premium' or lower(btrim(name))=lower('Spotify Premium')) on conflict do nothing;
insert into public.products (id, name, description, category, price, duration, image, active, slug, old_price, promotion_enabled, promo_starts_at, promo_ends_at, is_featured, sort_order, quote_only, details) select '10000000-0000-4000-8000-000000000108', 'CapCut Pro', 'Montage vidéo et création de contenus.', 'Création', 6500, 'Durée non précisée', '/services/capcut-pro.webp', true, 'capcut-pro', NULL, false, NULL, NULL, false, 6, false, '{"short_description":"Montage vidéo et création de contenus.","icon":"CC","whatsapp_enabled":true,"button_text":"Commander","order_instructions":"","order_fields":[],"kind":"subscription","stock":null,"unit":"","variant_label":"","delivery_info":"","archived_at":null}' where not exists (select 1 from public.products where id='10000000-0000-4000-8000-000000000108' or slug='capcut-pro' or lower(btrim(name))=lower('CapCut Pro')) on conflict do nothing;
insert into public.products (id, name, description, category, price, duration, image, active, slug, old_price, promotion_enabled, promo_starts_at, promo_ends_at, is_featured, sort_order, quote_only, details) select '10000000-0000-4000-8000-000000000107', 'Monétisation TikTok', 'Accompagnement pour la création et la configuration d’un compte TikTok éligible.', 'Réseaux sociaux', 15000, 'Service ponctuel', '/services/monetisation-tiktok.webp', true, 'monetisation-tiktok', NULL, false, NULL, NULL, false, 7, false, '{"short_description":"Accompagnement pour la création et la configuration d’un compte TikTok éligible.","icon":"TT","whatsapp_enabled":true,"button_text":"Commander","order_instructions":"","order_fields":[],"kind":"digital","stock":null,"unit":"","variant_label":"","delivery_info":"","archived_at":null}' where not exists (select 1 from public.products where id='10000000-0000-4000-8000-000000000107' or slug='monetisation-tiktok' or lower(btrim(name))=lower('Monétisation TikTok')) on conflict do nothing;
insert into public.shop_settings (id, name, whatsapp_number, email, logo_url, welcome_text, wave_number, wave_name, orange_money_number, orange_money_name, delivery_info, social_links) select 1, 'TerangaZone', '221781108729', '', NULL, 'Tout votre univers numérique au même endroit.', '76 993 83 04', 'TerangaZone', '78 110 87 29', 'TerangaZone', 'Traitement après confirmation du paiement. Les accès et instructions sont transmis sur WhatsApp.', '[]' on conflict do nothing;
commit;
